### ISSUE TITLE
Docker repository in private mode ?

### ISSUE THREAD

**Issue by Lordingard** [aunefyren/poenskelisten#2]
Hello,

When I want to deploy the Docker image, I have this message :

`aunefyren/poenskelisten:latest
Unable to find image 'true:latest' locally
docker: Error response from daemon: pull access denied for true, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

The repository seem to be in private mode.
Is it normal ?

Thank you.

**Comment by aunefyren** [comment]
Hey, are you able to share the Docker run command or docker-compose file you used? I need to validate if the repo was typed correctly and what registry you are pulling Docker images from.

Based on your error it seems it tried to download `true:latest` not `aunefyren/poenskelisten:latest` or am I misinterpreting that?

The repo does look public to me, so am not sure what the issue is currently.

**Comment by Lordingard** [comment]
Hi,

This is strange because the pull work with "docker pull aunefyren/poenskelisten:latest" but in my docker run command, it try to down load true:latest and not use the pulled image.
I don't know why.

Here my run command : 
 
`docker run -d \
--name=poenskelisten \
--network dockernet \
--hostname poenskelisten \
--restart=always \
-e generateinvite: true \
-e port=8080 \
-e timezone: Europe/Paris \
-e TZ=Europe/Paris \
-e dbip: mariadb \
-e dbport: 3306 \
-e dbname: DBNAME \
-e dbusername: USERNAME \
-e dbpassword: PASSWORD \
-v /poenskelisten/:/app/files/ \
aunefyren/poenskelisten:latest`

**Comment by Lordingard** [comment]
Hi,
I noted some errors in my run commands, sorry about that -_-
